// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efgtvoejpiqeitulixlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmZ3R2b2VqcGlxZWl0dWxpeGxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMzMxNzMsImV4cCI6MjA2NDgwOTE3M30.wo1aVEyzqLNgOZYKczj5DbWZRaZ1YMqRWOBdoLOIr10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);